# general
name: MambaIRv2_OAT_p32_x1        # 可把 p32 改成实际 SPARSE_PROJ
model_type: MambaIRv2Model
scale: 1   #4
num_gpu: 1 #8
manual_seed: 10

# datasets
datasets:
  train:
    task: IR
    name: OAT_mice_train
    type: PairedImageDataset
    dataroot_gt:
      - /root/autodl-tmp/mambaIR2/MambaIR/datasets/Nature_Davoudi/GT_LQsparse32/train_bic/HR/X1
    dataroot_lq:
      - /root/autodl-tmp/mambaIR2/MambaIR/datasets/Nature_Davoudi/GT_LQsparse32/train_bic/LR/X1
    io_backend: { type: disk }
    gt_size: 128                  #192
    use_hflip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 32     #32
    batch_size_per_gpu: 1     #4
    dataset_enlarge_ratio: 100

  val:
    name: OAT_mice_valid
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/mambaIR2/MambaIR/datasets/Nature_Davoudi/GT_LQsparse32/valid_bic/HR/X1
    dataroot_lq: /root/autodl-tmp/mambaIR2/MambaIR/datasets/Nature_Davoudi/GT_LQsparse32/valid_bic/LR/X1
    io_backend: { type: disk }

# network
network_g:
  type: MambaIRv2
  upscale: 1
  in_chans: 3                # 单通道光声
  img_size: 64
  img_range: 1.
  embed_dim: 174     #174
  d_state: 16
  depths: [6,6,6,6,6,6]
  num_heads: [6,6,6,6,6,6]
  window_size: 16   #16
  inner_rank: 64
  num_tokens: 128
  convffn_kernel_size: 5
  mlp_ratio: 2.
  upsampler: ''              # 关闭 pixelshuffle（scale=1）
  resi_connection: '1conv'

  # 双扫描
  dual_scan: true
  use_guidance: true
  scan_opts:
    stripe: 8
    kappa: 1.0
    block_base: 8
    ds: 2
    interleave: [3, 1]
    steps: 3
    #fusion:temporal
    #fuse: [2, 1]               # 融合节奏：2步 CSH + 1步 RACS（控制“时域交错”融合）
    
# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# train
train:
  optim_g: { type: Adam, lr: !!float 1e-4, weight_decay: 0, betas: [0.9, 0.99] }
  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 225000, 237500]
    gamma: 0.5
  total_iter: 250000
  warmup_iter: -1
  pixel_opt: { type: L1Loss, loss_weight: 1.0, reduction: mean }

# val
val:
  val_freq: !!float 5e3
  save_img: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true

logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb: { project: ~, resume_id: ~ }

dist_params: { backend: nccl, port: 29500 }
dist: true
