name: MambaIRv2_CAR_q40
model_type: MambaIRv2Model
scale: 1
num_gpu: 1
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    task: CAR
    name: Nature_Davoudi
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/mambaIR2/MambaIR/datasets/Nature_Davoudi/GT_LQsparse32/train_bic/HR/X1
    dataroot_lq: /root/autodl-tmp/mambaIR2/MambaIR/datasets/Nature_Davoudi/GT_LQsparse32/train_bic/LR/X1
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 126
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    task: CAR
    name: Nature_Davoudi
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/mambaIR2/MambaIR/datasets/Nature_Davoudi/GT_LQsparse32/valid_bic/HR/X1
    dataroot_lq: /root/autodl-tmp/mambaIR2/MambaIR/datasets/Nature_Davoudi/GT_LQsparse32/valid_bic/LR/X1
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: MambaIRv2
  upscale: 1
  in_chans: 1
  img_size: 126
  embed_dim: 174
  d_state: 16
  depths: [6, 6, 6, 6, 6, 6]
  num_heads: [6, 6, 6, 6, 6, 6]
  window_size: 16
  inner_rank: 64
  num_tokens: 128
  convffn_kernel_size: 5
  mlp_ratio: 2.0

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4 # for jpeg 40
    # lr: !!float 1e-4 # for jpeg 30/10
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 800000, 1200000, 1400000, 1500000 ] # for jpeg 40
    # milestones: [ 400000, 600000, 700000, 750000 ] # for jpeg 10/30
    gamma: 0.5

  total_iter: 1600000 # for jpeg 40
  # total_iter: 800000 # for jpeg 10/30
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
    eps: !!float 1e-3

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
